import Page from 'flarum/common/components/Page';
import type Mithril from 'mithril';
type Slide = {
    type: string;
    key?: string;
    data?: any;
};
export default class CommunitySlideshow extends Page {
    loading: boolean;
    snapshot: any;
    data: Record<string, any> | null;
    prevData: Record<string, any> | null;
    currentSlide: number;
    direction: number;
    animating: boolean;
    slides: Slide[];
    touchStartX: number;
    isDestroyed: boolean;
    oninit(vnode: Mithril.Vnode): void;
    getYear(): number;
    loadSnapshot(): Promise<void>;
    oncreate(vnode: Mithril.VnodeDOM): void;
    onremove(vnode: Mithril.VnodeDOM): void;
    onKeyDown: (e: KeyboardEvent) => void;
    onupdate(vnode: Mithril.VnodeDOM): void;
    private lastAnimatedSlide;
    runAnimations(root: Element): void;
    animateHeader(root: Element): void;
    animateIntroSlide(root: Element): void;
    animateSummarySlide(root: Element): void;
    animateCountUpSlide(root: Element): void;
    animateChartSlide(root: Element): void;
    animateClockSlide(root: Element): void;
    animateUserListSlide(root: Element): void;
    animatePreviewSlide(root: Element): void;
    animateSpotlightSlide(root: Element): void;
    animateAvatarGridSlide(root: Element): void;
    goBack(): void;
    next(): void;
    prev(): void;
    handleClick(e: MouseEvent): void;
    handleTouchStart(e: TouchEvent): void;
    handleTouchEnd(e: TouchEvent): void;
    view(): Mithril.Children;
    renderSlide(slide: Slide): Mithril.Children;
    renderIntro(): Mithril.Children;
    renderChangeIndicator(current: number, previous: number | undefined): Mithril.Children;
    renderEmpty(): Mithril.Children;
    renderYearOverview(): Mithril.Children;
    renderBusiestMonth(): Mithril.Children;
    renderPeakHour(): Mithril.Children;
    renderUserCard(userId: number, username: string, subtitle: string, index: number): Mithril.Children;
    renderTopContributors(): Mithril.Children;
    renderMostLoved(): Mithril.Children;
    renderStarPost(): Mithril.Children;
    renderTopDiscussion(): Mithril.Children;
    renderTopTag(): Mithril.Children;
    renderTotalWords(): Mithril.Children;
    renderNewMembers(): Mithril.Children;
    renderBestAnswersLeaderboard(): Mithril.Children;
    renderBadgeLeaderboard(): Mithril.Children;
    renderSummary(): Mithril.Children;
    share(): Promise<void>;
}
export {};
