import Page from 'flarum/common/components/Page';
import type Mithril from 'mithril';
export default class SlideshowPage extends Page {
    loading: boolean;
    snapshot: any;
    snapshotData: Record<string, any> | null;
    currentSlide: number;
    direction: number;
    animating: boolean;
    slides: Array<{
        type: string;
        key?: string;
        data?: any;
    }>;
    touchStartX: number;
    touchStartY: number;
    isDestroyed: boolean;
    isMetricEmpty(key: string, d: any): boolean;
    oninit(vnode: Mithril.Vnode): void;
    loadSnapshot(): Promise<void>;
    oncreate(vnode: Mithril.VnodeDOM): void;
    onremove(vnode: Mithril.VnodeDOM): void;
    onKeyDown: (e: KeyboardEvent) => void;
    onupdate(vnode: Mithril.VnodeDOM): void;
    private lastAnimatedSlide;
    runSlideAnimations(root: Element): void;
    animateIntro(root: Element): void;
    animateSummary(root: Element): void;
    animateMetricSlide(root: Element, key: string, layout: string): void;
    goBack(): void;
    next(): void;
    prev(): void;
    handleClick(e: MouseEvent): void;
    handleTouchStart(e: TouchEvent): void;
    handleTouchEnd(e: TouchEvent): void;
    togglePublic(): Promise<void>;
    renderAmbientShapes(): Mithril.Children;
    view(): Mithril.Children;
    renderIntro(): Mithril.Children;
    renderEmpty(): Mithril.Children;
    splitText(text: string, className: string): Mithril.Children;
    renderMetricSlide(key: string, data: Record<string, any>): Mithril.Children;
    renderBignumContent(key: string, data: Record<string, any>): Mithril.Children;
    renderBadgesContent(data: Record<string, any>): Mithril.Children;
    renderSpotlightContent(key: string, data: Record<string, any>): Mithril.Children;
    renderQuoteContent(data: Record<string, any>): Mithril.Children;
    renderClockContent(data: Record<string, any>): Mithril.Children;
    renderHeartContent(key: string, data: Record<string, any>): Mithril.Children;
    renderPersonContent(key: string, data: Record<string, any>): Mithril.Children;
    renderChartContent(data: Record<string, any>): Mithril.Children;
    renderWordsSlide(data: Record<string, any>): Mithril.Children;
    renderEmojiChar(emoji: string): Mithril.Children;
    renderEmojisSlide(data: Record<string, any>): Mithril.Children;
    renderSummary(): Mithril.Children;
    share(): Promise<void>;
    renderSummaryValue(key: string, data: Record<string, any>): Mithril.Children;
    getSummaryValue(key: string, data: Record<string, any>): string;
}
